version: '4.2.23'
services:
  database_TATUGA_SCHOOL:
    # This image automatically creates a replica set required for transactions
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      MONGO_REPLICA_HOST: host.docker.internal
      INIT_WAIT_SEC: 3
    ports:
      - 27017:27017
  # Added Redis service
  redis_TATUGA:
    image: redis:7-alpine
    container_name: redis-test
    restart: always
    ports:
      - 6379:6379
    # Healthcheck ensures the container is ready before other services use it
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5
