# Base image
FROM oven/bun:latest

# Create app directory
WORKDIR /usr/src/app

# A wildcard is used to ensure both package.json AND bun.lock are copied
COPY package*.json bun.lock* ./

# Install app dependencies
ENV NODE_ENV=test
RUN bun install --ci
COPY prisma ./prisma/
RUN bunx prisma generate
RUN bun install -g @nestjs/cli
# Bundle app source
COPY . .

# Copy the .env and .env.development files



# Creates a "dist" folder with the production build
RUN bun run build



# Start the server using the production build
CMD ["bun", "run", "start:prod"]
